server:
  port: 0

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  datasource:
    url: jdbc:mariadb://192.168.3.8:3306/test
    username: test
    password:
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000

logging:
  level:
    root: debug
