eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:8761/eureka/

spring:
  datasource:
    url: jdbc:mariadb://192.168.3.8:3306/test
    username: test
    password:
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  rabbitmq:
    host: 192.168.3.8
    port: 5672
    username: admin
    password: admin
  cloud:
    bootstrap: 
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

# logging:
#   level:
#     root: debug
