spring:
  application:
    name: external
  ai: 
    openai: 
      api-key: 
      chat:
        options:
          model: gpt-4o
          temperature: 0.7

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 0
