redmine:
  base-url: https://issue.direa.synology.me
  api-key: 2

gitlab:
  base-url: https://gitlab.direa.synology.me/api/v4
  private-token: glpat-

spring:
  application:
    name: external
  ai: 
    openai: 
      api-key: sk-
      chat:
        options:
          model: gpt-4o
          temperature: 0.7

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 0
