keycloak:
  base-url: https://keycloak.direa.synology.me
  realm: sso
  admin-client:
    client-id: chrome-api
    client-secret: 9

spring:
  application:
    name: workspace
  config:
    activate:
      on-profile: local

  jpa: 
    defer-datasource-initialization: true
  sql: 
    init: 
      mode: always

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 8080
